### ISSUE TITLE
Does this project works for GPT-like model to do text generation?

### ISSUE THREAD

**Issue by PanQiWei** [usc-isi/PipeEdge#16]
Hi! Execuse me, I wonder if this project works for models like GPT to do text generation? If not, could you share any ideas that I can try to modify this project so that it can fit text generation task?

**Comment by cimes-isi** [comment]
I haven't looked at GPT models, but my understanding is that they are built using transformers, like the models we've evaluated.  As long as the model only moves data forward between layers during inference, then conceptually PipeEdge should be able to support it.  The devices you deploy a pipeline onto will still have to be large enough to support at least one model layer, which might still be relatively large for some GPT models.

To modify PipeEdge to support a new transformer model, the most straightforward approach is to add a new file in the `src/pipeedge/models/transformers` directory and implement a Model class that supports loading only a subset of the weights.  For example, we first export model model weights as a .npz file on a computer that can fit the whole model in memory, then load layers from the npz file as needed when actually deploying a pipeline.  See the existing files for examples -- there are probably better approaches than we've taken, but that's what we have implemented to date.

**Comment by cimes-isi** [comment]
For legacy reasons, PipeEdge supports two different communication protocols - `rpc` and `p2p`.  The `p2p` protocol (now the default in our example `runtime.py`) preserves input/output ordering, making for a FIFO pipeline. The example runtime loops the inference results from the last stage of the pipeline back to the "data rank"---the device where the inputs come from (and often the stage with the first model shard in the pipeline).  The example runtime loops the results back like this so it knows when all the data has been processed and it can shut down the pipeline and terminate the application gracefully.  A trivial example of a 4-stage pipeline would be to setup the pipeline in rank order so data flows from ranks: 0 -> 1 -> 2 -> 3 -> 0.  It sounds like you want something similar -- you could have the front of the pipeline keep track of (i.e., count) input and output microbatches and correlate them with cached metadata.  This works as long as long as there aren't any errors in the pipeline.

There's also nothing preventing you from passing the additional metadata through the pipeline along with each microbatch.  For example, you could pack your metadata into 1 or more additional tensors that your model knows how to handle (or likely just ignore) and forward those metadata tensors along with the intermediate data tensors.

**Comment by PanQiWei** [comment]
Great! I think your work solved my biggest concern to design a pipeline parallelism inference engine for tasks like text generation.
